watermark:
  position: [1226, 704, 1273, 713]
  mask_expand: 10
  neighbor_stride: 5
  ckpt_p: "./weights/sttn.pth"

enhance:
  RealESRGAN_model_path: "./weights/RealESRGAN_x2plus.pth"
  GFPGANer_model_path: "./weights/GFPGANv1.4.pth"
